# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-04 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('score', models.CharField(max_length=8)),
                ('img_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('language', models.CharField(max_length=16)),
                ('hall', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('cinema', models.CharField(max_length=64)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('糯米', '糯米'), ('时光', '时光'), ('淘票票', '淘票票')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='TppCinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('荔湾区', '荔湾区'), ('黄埔区', '黄埔区'), ('天河区', '天河区'), ('白云区', '白云区'), ('越秀区', '越秀区'), ('海珠区', '海珠区'), ('从化区', '从化区'), ('番禺区', '番禺区'), ('花都区', '花都区'), ('萝岗区', '萝岗区'), ('南沙区', '南沙区'), ('增城区', '增城区')], max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('tpp_id', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'tppcinema',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Source'),
        ),
    ]
