# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20181205_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_hot',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.CharField(default='0', max_length=8),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.CharField(max_length=16),
        ),
    ]
