# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 08:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20181205_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.date(2018, 12, 5)),
        ),
    ]
